### ISSUE TITLE
improvements for guitartab

### ISSUE THREAD

**Issue by e-dschungel** [workinghard/GuitarTeX2#2]
Hi,

here are two suggestions to improve the guitartab output:

1. Change `gtxtabs` to the following to allow a broken line
```latex
\newcommand{\gtxtabs}[2]{{\makebox[0cm][l]{\raisebox{#1}{\colorbox{white}{#2}}}}}
```
Before:
![image](https://user-images.githubusercontent.com/601056/113567773-8251b200-960f-11eb-9b5d-f1e14e4e4583.png)

After:
![image](https://user-images.githubusercontent.com/601056/113567915-ccd32e80-960f-11eb-9085-2825f8dd4c29.png)

2. Change fixed length (130mm) of guitartab (and bass tab) to \textwidth. This improves portability to different paper size. I use A5 for instance so 130mm is too long.
```latex
\newcommand{\guitartab}{%
\makebox[0cm][l]{\raisebox{12.5ex}{\footnotesize{e}}}%
\makebox[0cm][l]{\raisebox{10.5ex}{\footnotesize{H}}}%
\makebox[0cm][l]{\raisebox{8.5ex}{\footnotesize{G}}}%
\makebox[0cm][l]{\raisebox{6.5ex}{\footnotesize{D}}}%
\makebox[0cm][l]{\raisebox{4.5ex}{\footnotesize{A}}}%
\makebox[0cm][l]{\raisebox{2.5ex}{\footnotesize{E}}}%
~~
\makebox[0cm][l]{\raisebox{13ex}{\line(1,0){\textwidth}}}%
\makebox[0cm][l]{\raisebox{11ex}{\line(1,0){\textwidth}}}%
\makebox[0cm][l]{\raisebox{9ex}{\line(1,0){\textwidth}}}%
\makebox[0cm][l]{\raisebox{7ex}{\line(1,0){\textwidth}}}%
\makebox[0cm][l]{\raisebox{5ex}{\line(1,0){\textwidth}}}%
\makebox[0cm][l]{\raisebox{3ex}{\line(1,0){\textwidth}}}%
~}
```
I personally implemented these changes by redefining the commands using `\renewcommand`. If they would be implemented in the software more people could profit from these.

**Comment by workinghard** [comment]
Hi @e-dschungel and thanks for contribution. textwidth will be included in the next release. 
White box doesn't work well for some cases. Please have a look at the lazy blues example:
<img width="670" alt="Bildschirmfoto 2022-01-06 um 22 07 35" src="https://user-images.githubusercontent.com/872831/148452474-a86f1e1d-6c66-4315-920f-4b5b7cb821c0.png">

Any ideas how to solve this are very welcome.

**Comment by e-dschungel** [comment]
Hi @workinghard,
one suggestion would be:
```latex
\newcommand{\gtxtabs}[2]{{\makebox[0cm][l]{\raisebox{#1}{\setlength{\fboxsep}{0pt}\colorbox{white}{#2}}}}}
```
This leads to:
![grafik](https://user-images.githubusercontent.com/601056/148567950-d6cd42ff-a52d-4fdf-a6f3-9c390664890c.png)

This decreases both the vertical and the horizontal margin and might have side effects as fboxsep is modified.

I assume a better solution (vertical tweaking independent of horizontal tweaking, local setting only) could be done using adjustbox, but it seems that it is not installed on your server:
```latex
\newcommand{\gtxtabs}[2]{{\makebox[0cm][l]{\raisebox{#1}{\adjustbox{margin=1ex 0ex, bgcolor=white}{#2}}}}}
```

**Comment by workinghard** [comment]
adjustbox package is installed but not included in the header. Something I will add to the next release.
I kind of like the look of ```\newcommand{\gtxtabs}[2]{{\makebox[0cm][l]{\raisebox{#1}{\adjustbox{margin=0ex 0ex, bgcolor=white}{#2}}}}}``` 
![image](https://user-images.githubusercontent.com/872831/148747809-c6547b54-75e3-4b88-b9a1-7c45d5c368c8.png)

Will need to compare to regenerate all my songs and check if it breaks something.

**Comment by e-dschungel** [comment]
I prefer a slightly larger horizontal gap between the number and the line. But never mind, I can tweak it for myself once adjustbox is in the header ;)

**Comment by workinghard** [comment]
Fair enough. Thanks for your contribution!
