### ISSUE TITLE
guitartex2.nikolai-rinas.de Port 3121

### ISSUE THREAD

**Issue by e-dschungel** [workinghard/GuitarTeX2#4]
Hi Nikolai,

it's me ;-) 
The server guitartex2.nikolai-rinas.de Port 3121 is currently not reachable so the conversion to PDF is not working. Is there a new address or did you stop to provide this service?

Regards
e-dschungel

**Comment by workinghard** [comment]
Hi. Should be up and running again. Thanks for checking.

**Comment by e-dschungel** [comment]
Wow, that was quick. Its working again. Thanks!

**Comment by e-dschungel** [comment]
And it stopped working ;)

**Comment by workinghard** [comment]
Very strange. Activated some more logging to check the root cause. Thanks for reporting.
